[build]
  base = "/"
  publish = "data/pages"
  functions = "lib/plugins"
  command = "echo 'No build command'"
  # You might need to specify your build command here if you have any preprocessing steps

[[redirects]]
  from = "/*"
  to = "/doku.php/:splat"
  status = 200
